### ISSUE TITLE
"Cannot stat [...]" errors when compiling kernel (A13 branch)

### ISSUE THREAD

**Issue by rdtm443** [ArrowOS-Devices/android_kernel_xiaomi_nabu#1]
Hey there !

I tried to compile the kernel from sources, but got the following error messages:

![image](https://user-images.githubusercontent.com/25002690/200546664-a4ac962b-cf18-493a-a2d5-44fe9abe69c0.png)

Are you really using this source here, or a fork for the Mi Pad 5 (nabu)? 

Thanks a lot.

Best

**Comment by justks** [comment]
Obviously, arrowos build servers use sources from here. 
Your issue is not related to Arrow, use aosp clang it should work or compile within ArrowOS source
